### ISSUE TITLE
Add a preview feature

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/LightsOff#64]
Maybe we can use the right mouse button to preview the effect of pressing a light button, with the flipped buttons shown as being pressed down. To commit the move, release the right mouse button on the clicked light button. To cancel, release it elsewhere.

**Comment by humdingerb** [comment]
I've had a similar idea before. But now that you've implemented moving through the "move-history" we have unlimited undo/redo. There's really no need for a preview, as you can just make a move and just click again to undo it.
Right-clicking and highlighting etc. seems to add unnecessary complexity.

**Comment by owenca** [comment]
I agree. :)
